[package]
name = "kate"
version = "0.1.0"
authors = ["Denis Ermolin <denis.ermolin@matic.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dusk-plonk = { version = "0.8.2", default-features = false, optional = true }
dusk-bytes = { version = "0.1.5", default-features = false, optional = true }
bls12_381 = { version = "0.3.1", optional = true   }
sp-std = { version = "3.0.0", default-features = false, path = "../../primitives/std", optional = true }
getrandom = { version = "0.2", features = ["js"], optional = true }
frame-support = { version = "3.0.0", default-features = false, path = "../../frame/support", optional = true }
rand = { version = "0.8.4", default-features = false, optional = true }
rand_core = {version="0.5", default-features=false}
rand_chacha = { version = "0.3", default-features = false, optional = true }
log = { version = "0.4.8", optional = true }
rayon = { version = "1.5.0", optional = true }
num_cpus = { version = "1.13.0", optional = true }
serde = { version = "1.0.121", optional = true, features = ["derive"] }

[features]
default = ["std"]
alloc = ["dusk-plonk/alloc"]

std = [
	"alloc",
	"serde",
	"num_cpus",
	"rayon",
	"bls12_381",
	"getrandom",
	"rand",
	"rand_chacha/std",
	"log",
	"dusk-plonk/std",
	"dusk-bytes",
	"sp-std/std",
	"getrandom/std",
	"rand_core/std",
	"frame-support/std"
]
