[package]
name = "node-template"
version = "2.0.0"
authors = ["Anonymous"]
description = "Polygon Data Avilability Node."
edition = "2018"
license = "GNU GPLv3"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/maticnetwork/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-template"

[dependencies]
structopt = "0.3.8"
rand = "0.8.2"
sc-cli = { version = "0.8.0", path = "../../../client/cli", features = ["wasmtime"] }
sp-core = { version = "2.0.0", path = "../../../primitives/core" }
sp-io = { version = "2.0.0", path = "../../../primitives/io" }
sc-executor = { version = "0.8.0", path = "../../../client/executor", features = ["wasmtime"] }
sc-service = { version = "0.8.0", path = "../../../client/service", features = ["wasmtime"] }
sc-keystore = { version = "2.0.0", path = "../../../client/keystore" }
sp-inherents = { version = "2.0.0", path = "../../../primitives/inherents" }
sc-transaction-pool = { version = "2.0.0", path = "../../../client/transaction-pool" }
sp-transaction-pool = { version = "2.0.0", path = "../../../primitives/transaction-pool" }
sc-consensus-babe = { version = "0.8.0", path = "../../../client/consensus/babe" }
sp-consensus-babe = { version = "0.8.0", path = "../../../primitives/consensus/babe" }
sp-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
sc-consensus = { version = "0.8.0", path = "../../../client/consensus/common" }
sc-finality-grandpa = { version = "0.8.0", path = "../../../client/finality-grandpa" }
sp-finality-grandpa = { version = "2.0.0", path = "../../../primitives/finality-grandpa" }
sc-client-api = { version = "2.0.0", path = "../../../client/api" }
sp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }
sp-std = { version = "2.0.0", default-features = false, path = "../../../primitives/std" }
sp-rpc = { version = "2.0.0", path = "../../../primitives/rpc" }
dusk-plonk = { path = "../../../client/plonk" }
kate = { path = "../../../client/kate", default-features = false }
log = "0.4.8"
lru = { version = "0.6.4"}
codec = { package = "parity-scale-codec", version = "1.3.4" }
frame-system = { package = "frame-system", path = "../../../frame/system"}
frame-support = { package = "frame-support", path = "../../../frame/support"}

# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"
sc-rpc = { version = "2.0.0", path = "../../../client/rpc" }
sp-api = { version = "2.0.0", path = "../../../primitives/api" }
sc-rpc-api = { version = "0.8.0", path = "../../../client/rpc-api" }
sp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
sp-block-builder = { version = "2.0.0", path = "../../../primitives/block-builder" }
sc-basic-authorship = { version = "0.8.0", path = "../../../client/basic-authorship" }
substrate-frame-rpc-system = { version = "2.0.0", path = "../../../utils/frame/rpc/system" }
pallet-transaction-payment-rpc = { version = "2.0.0", path = "../../../frame/transaction-payment/rpc/" }
pallet-im-online = { version = "2.0.0", default-features = false, path = "../../../frame/im-online" }
pallet-staking = { version = "2.0.0", default-features = false, path = "../../../frame/staking" }


# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "2.0.0", path = "../../../frame/benchmarking" }
frame-benchmarking-cli = { version = "2.0.0", path = "../../../utils/frame/benchmarking-cli" }

node-template-runtime = { version = "2.0.0", path = "../runtime" }
kate-rpc-runtime-api = { path = "../pallets/kate-rpc-runtime-api" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0", path = "../../../utils/build-script-utils" }

[features]
default = []
runtime-benchmarks = [
	"node-template-runtime/runtime-benchmarks",
]
