[package]
name = "node-template-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"
license = "GNU GPLv3"
homepage = "https://substrate.dev"
repository = "https://github.com/maticnetwork/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
static_assertions = "1.1.0"
kate = { path = "../../../client/kate", default-features = false }
pallet-aura = { version = "3.0.0", default-features = false, path = "../../../frame/aura" }
pallet-balances = { version = "3.0.0", default-features = false, path = "../../../frame/balances" }
frame-support = { version = "3.0.0", default-features = false, path = "../../../frame/support" }
pallet-grandpa = { version = "3.0.0", default-features = false, path = "../../../frame/grandpa" }
pallet-randomness-collective-flip = { version = "3.0.0", default-features = false, path = "../../../frame/randomness-collective-flip" }
pallet-sudo = { version = "3.0.0", default-features = false, path = "../../../frame/sudo" }
frame-system = { version = "3.0.0", default-features = false, path = "../../../frame/system" }
pallet-timestamp = { version = "3.0.0", default-features = false, path = "../../../frame/timestamp" }
pallet-transaction-payment = { version = "3.0.0", default-features = false, path = "../../../frame/transaction-payment" }
frame-executive = { version = "3.0.0", default-features = false, path = "../../../frame/executive" }
pallet-staking-reward-curve = { version = "3.0.0", default-features = false, path = "../../../frame/staking/reward-curve" }
pallet-authorship = { version = "3.0.0", default-features = false, path = "../../../frame/authorship" }
pallet-offences = { version = "3.0.0", default-features = false, path = "../../../frame/offences" }
pallet-collective = { version = "3.0.0", default-features = false, path = "../../../frame/collective" }
pallet-authority-discovery = { version = "3.0.0", default-features = false, path = "../../../frame/authority-discovery" }
pallet-membership = { version = "2.0.0", default-features = false, path = "../../../frame/membership" }
pallet-scheduler = { version = "2.0.0", default-features = false, path = "../../../frame/scheduler" }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "3.0.0", default-features = false, path = "../../../primitives/api" }
sp-block-builder = { path = "../../../primitives/block-builder", default-features = false, version = "3.0.0"}
sp-consensus-aura = { version = "0.9.0", default-features = false, path = "../../../primitives/consensus/aura" }
sp-core = { version = "3.0.0", default-features = false, path = "../../../primitives/core" }
sp-inherents = { path = "../../../primitives/inherents", default-features = false, version = "3.0.0"}
sp-offchain = { version = "3.0.0", default-features = false, path = "../../../primitives/offchain" }
sp-runtime = { version = "3.0.0", default-features = false, path = "../../../primitives/runtime" }
sp-session = { version = "3.0.0", default-features = false, path = "../../../primitives/session" }
sp-std = { version = "3.0.0", default-features = false, path = "../../../primitives/std" }
sp-transaction-pool = { version = "3.0.0", default-features = false, path = "../../../primitives/transaction-pool" }
sp-version = { version = "3.0.0", default-features = false, path = "../../../primitives/version" }
kate-rpc-runtime-api = { path = "../pallets/kate-rpc-runtime-api", default-features = false }
sp-io = { version = "2.0.0", path = "../../../primitives/io", default-features = false }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { version = "3.0.0", default-features = false, path = "../../../frame/system/rpc/runtime-api/" }
pallet-transaction-payment-rpc-runtime-api = { version = "3.0.0", default-features = false, path = "../../../frame/transaction-payment/rpc/runtime-api/" }

# Used for runtime benchmarking
frame-benchmarking = { version = "3.0.0", default-features = false, path = "../../../frame/benchmarking", optional = true }
frame-system-benchmarking = { version = "3.0.0", default-features = false, path = "../../../frame/system/benchmarking", optional = true }
hex-literal = { version = "0.3.1", optional = true }

da = { version = "2.0.0", default-features = false, path = "../pallets/template", package = "polygon-data-availability" }

[build-dependencies]
substrate-wasm-builder = { version = "4.0.0", path = "../../../utils/wasm-builder" }

[features]
default = ["std"]
std = [
	"kate-rpc-runtime-api/std",
	"sp-io/std",
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"pallet-babe/std",
	"pallet-balances/std",
	"pallet-authority-discovery/std",
	"pallet-grandpa/std",
	"pallet-indices/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-im-online/std",
	"pallet-randomness-collective-flip/std",
	"pallet-sudo/std",
	"pallet-session/std",
	"pallet-elections-phragmen/std",
	"pallet-staking/std",
	"pallet-treasury/std",
	"pallet-democracy/std",
	"pallet-bounties/std",
	"pallet-authorship/std",
	"pallet-offences/std",
	"pallet-collective/std",
	"pallet-scheduler/std",
	"pallet-utility/std",
	"pallet-membership/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-authority-discovery/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"da/std",
]
runtime-benchmarks = [
	"sp-runtime/runtime-benchmarks",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking",
	"hex-literal",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
]
